<a href="https://colab.research.google.com/github/kalpesh5536/mental-health-platform-analytics/blob/main/Data_analyst_intern.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import all necessary things

- **500 user id** :- for 1st time it is given and for next time if coming then same user id and if some other person came then new user id. in short Unique id for each user.
- **1095 session id** :-  number of time people took session.
- **session date** :- when they visited
- **session number** :- its there 1st time or 2nd or 3rd it stores that details
- **Therapiest ID** :- which doctor is treating their id
- **Fee** :- How much fee is charged
- **Cohert month** :- Which month user came
- **Signup Date** :- When they first time registerd
- **Source** :- By which social media they come to know about this
- **Rating** :- Rating given by user after therapy sessions
- **Review text** :- review given by user in text
- **Sequence check** :- Checks whether session numbers are in correct order
- **Retained** :- this tells  whether user came back or not
- **User Life time sessions** :- Total sessions attended by a user
- **Average rating** :- Average rating given by  user
- **Days between sessions** :- Time gap between two sessions

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
feedback_url= "https://raw.githubusercontent.com/kalpesh5536/mental-health-platform-analytics/refs/heads/main/Feedback.csv"

sessions_url= "https://raw.githubusercontent.com/kalpesh5536/mental-health-platform-analytics/refs/heads/main/Sessions.csv"

user_url= "https://raw.githubusercontent.com/kalpesh5536/mental-health-platform-analytics/refs/heads/main/Users.csv"

feedback= pd.read_csv(feedback_url)
sessions= pd.read_csv(sessions_url)
users= pd.read_csv(user_url)

print(feedback.head())

   session_id  rating         review_text
0           1       3  Sample review text
1           2       5  Sample review text
2           3       5  Sample review text
3           4       2  Sample review text
4           6       5  Sample review text

**print data**

In [ ]:
print(sessions.head())

   session_id  user_id session_date  session_number  therapist_id   fee
0           1        1   2025-04-27               1            46  1000
1           2        2   2025-07-04               1            35   700
2           3        3   2025-04-15               1            26   500
3           4        4   2025-01-19               1            41  1000
4           5        4   2025-01-28               2            45   700

In [ ]:
print(users.head())

   user_id signup_date     source
0        1  2025-04-13     Google
1        2  2025-06-29  Instagram
2        3  2025-04-03     Google
3        4  2025-01-15  Instagram
4        5  2025-04-17    Organic

In [ ]:
print(feedback.shape)
print(sessions.shape)
print(users.shape)

(898, 3)
(1095, 6)
(500, 3)

**Get info of all 3 ** and apply describe

In [ ]:
feedback.info()
feedback.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   session_id   898 non-null    int64
 1   rating       898 non-null    int64
 2   review_text  898 non-null    object
dtypes: int64(2), object(1)
memory usage: 21.2+ KB

        session_id      rating
count   898.000000  898.000000
mean    539.545657    3.040089
std     314.415943    1.412066
min       1.000000    1.000000
25%     266.250000    2.000000
50%     543.000000    3.000000
75%     807.750000    4.000000
max    1095.000000    5.000000

In [ ]:
sessions.info()
sessions.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   session_id      1095 non-null   int64
 1   user_id         1095 non-null   int64
 2   session_date    1095 non-null   object
 3   session_number  1095 non-null   int64
 4   therapist_id    1095 non-null   int64
 5   fee             1095 non-null   int64
dtypes: int64(5), object(1)
memory usage: 51.5+ KB

        session_id      user_id  session_number  therapist_id          fee
count  1095.000000  1095.000000     1095.000000   1095.000000  1095.000000
mean    548.000000   253.519635        2.006393     24.731507   733.789954
std     316.243577   144.858934        1.166627     14.003756   207.601810
min       1.000000     1.000000        1.000000      1.000000   500.000000
25%     274.500000   131.500000        1.000000     12.000000   500.000000
50%     548.000000   258.000000        2.000000     24.000000   700.000000
75%     821.500000   379.000000        3.000000     37.000000  1000.000000
max    1095.000000   500.000000        5.000000     49.000000  1000.000000

In [ ]:
users.info()
users.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      500 non-null    int64
 1   signup_date  500 non-null    object
 2   source       500 non-null    object
dtypes: int64(1), object(2)
memory usage: 11.8+ KB

          user_id
count  500.000000
mean   250.500000
std    144.481833
min      1.000000
25%    125.750000
50%    250.500000
75%    375.250000
max    500.000000

Checking for the Null values present or not

In [ ]:
feedback.isnull().sum()

session_id     0
rating         0
review_text    0
dtype: int64

In [ ]:
sessions.isnull().sum()

session_id        0
user_id           0
session_date      0
session_number    0
therapist_id      0
fee               0
dtype: int64

In [ ]:
users.isnull().sum()

user_id        0
signup_date    0
source         0
dtype: int64

checking any duplicate values present or not

In [ ]:
feedback.duplicated().sum()

np.int64(0)

In [ ]:
sessions.duplicated().sum()

np.int64(0)

In [ ]:
users.duplicated().sum()

np.int64(0)

convert string date to real data

In [ ]:
sessions['session_date']= pd.to_datetime(sessions['session_date'])
sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   session_id      1095 non-null   int64
 1   user_id         1095 non-null   int64
 2   session_date    1095 non-null   datetime64[ns]
 3   session_number  1095 non-null   int64
 4   therapist_id    1095 non-null   int64
 5   fee             1095 non-null   int64
dtypes: datetime64[ns](1), int64(5)
memory usage: 51.5 KB

In [ ]:
users['signup_date']=pd.to_datetime(users['signup_date'])
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      500 non-null    int64
 1   signup_date  500 non-null    datetime64[ns]
 2   source       500 non-null    object
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 11.8+ KB

**Now SQL all**

In [ ]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in /usr/local/lib/python3.12/dist-packages (0.5.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (7.34.0)
Requirement already satisfied: sqlalchemy>=2.0 in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (2.0.49)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable->ipython-sql) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)

In [ ]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [ ]:
%sql sqlite:///mydb.db

In [ ]:
import sqlite3
conne= sqlite3.connect("mental_health.db")


sessions.to_sql("sessions", conne, if_exists="replace", index=False)
users.to_sql("users", conne, if_exists= "replace", index=False)
feedback.to_sql("feedback",conne,if_exists="replace",index=False)

898

In [ ]:
pd.read_sql("select* from sessions", conne)

,session_id,user_id,session_date,session_number,therapist_id,fee
0,1,1,2025-04-27 00:00:00,1,46,1000
1,2,2,2025-07-04 00:00:00,1,35,700
2,3,3,2025-04-15 00:00:00,1,26,500
3,4,4,2025-01-19 00:00:00,1,41,1000
4,5,4,2025-01-28 00:00:00,2,45,700
...,...,...,...,...,...,...
1090,1091,496,2025-03-22 00:00:00,1,6,500
1091,1092,497,2025-03-17 00:00:00,1,5,700
1092,1093,498,2025-06-23 00:00:00,1,48,500
1093,1094,499,2025-06-25 00:00:00,1,2,500
1094,1095,500,2025-03-24 00:00:00,1,13,500

In [ ]:
pd.read_sql("select* from users", conne)

     user_id          signup_date     source
0          1  2025-04-13 00:00:00     Google
1          2  2025-06-29 00:00:00  Instagram
2          3  2025-04-03 00:00:00     Google
3          4  2025-01-15 00:00:00  Instagram
4          5  2025-04-17 00:00:00    Organic
..       ...                  ...        ...
495      496  2025-03-08 00:00:00     Google
496      497  2025-03-06 00:00:00   Referral
497      498  2025-06-10 00:00:00     Google
498      499  2025-06-17 00:00:00    Organic
499      500  2025-03-15 00:00:00     Google

[500 rows x 3 columns]

In [ ]:
pd.read_sql("select*from feedback", conne)

     session_id  rating         review_text
0             1       3  Sample review text
1             2       5  Sample review text
2             3       5  Sample review text
3             4       2  Sample review text
4             6       5  Sample review text
..          ...     ...                 ...
893        1091       5  Sample review text
894        1092       3  Sample review text
895        1093       5  Sample review text
896        1094       2  Sample review text
897        1095       4  Sample review text

[898 rows x 3 columns]

**all queries from assignment **

In [ ]:
# 1) Create a cohort based on month of first session

query = """
WITH UserCohorts AS (
    SELECT
        user_id,
        strftime('%Y-%m', MIN(session_date)) AS cohort_month
    FROM sessions
    GROUP BY user_id
)
SELECT
    cohort_month,
    COUNT(user_id) AS total_users
FROM UserCohorts
GROUP BY cohort_month
ORDER BY cohort_month;
"""

result = pd.read_sql_query(query, conne)
result

  cohort_month  total_users
0      2025-01           62
1      2025-02           74
2      2025-03           73
3      2025-04           91
4      2025-05           96
5      2025-06           89
6      2025-07           15

In [ ]:
# Calculate retention (%) for session 2, 3, 4
query = """
SELECT
    session_number,
    COUNT(DISTINCT user_id) AS users,
    ROUND(
        COUNT(DISTINCT user_id) * 100.0 /
        (SELECT COUNT(DISTINCT user_id)
         FROM sessions
         WHERE session_number = 1),
    2) AS retention_percentage
FROM sessions
WHERE session_number IN (1,2,3,4)
GROUP BY session_number
ORDER BY session_number;
"""

df = pd.read_sql_query(query, conne)
df

   session_number  users  retention_percentage
0               1    500                 100.0
1               2    281                  56.2
2               3    169                  33.8
3               4     97                  19.4

In [ ]:
# Q.3) Total users → users who completed session 1 → session 2 → session 3 and show conversion % at each step

query = """
WITH total_users AS (
    SELECT COUNT(DISTINCT user_id) AS users FROM users),
session1 AS (
    SELECT COUNT(DISTINCT user_id) AS users FROM sessions WHERE session_number=1),
session2 AS (
    SELECT COUNT(DISTINCT user_id) AS users FROM sessions WHERE session_number=2),
session3 AS (
    SELECT COUNT(DISTINCT user_id) AS users FROM sessions WHERE session_number=3)


SELECT 'Total Users' AS stage, users, 100.0 AS conversion_percentage FROM total_users

UNION ALL

SELECT 'Session 1', users,
ROUND(users * 100.0 / (SELECT users FROM total_users), 2)
FROM session1

UNION ALL

SELECT 'Session 2', users,
ROUND(users * 100.0 / (SELECT users FROM session1), 2)
FROM session2

UNION ALL

SELECT 'Session 3', users,
ROUND(users * 100.0 / (SELECT users FROM session2), 2)
FROM session3;

"""

pd.read_sql(query, conne)

         stage  users  conversion_percentage
0  Total Users    500                 100.00
1    Session 1    500                 100.00
2    Session 2    281                  56.20
3    Session 3    169                  60.14

In [ ]:
# Calculate:

# Total revenue
query = """
SELECT
    SUM(fee) AS total_revenue
FROM sessions;
"""

pd.read_sql(query, conne)

   total_revenue
0         803500

In [ ]:
# Revenue per user

query = """
SELECT
    user_id,
    SUM(fee) AS revenue_per_user
FROM sessions
GROUP BY user_id;
"""

df= pd.read_sql(query, conne)
df.head(20)

    user_id  revenue_per_user
0         1              1000
1         2               700
2         3               500
3         4              2200
4         5              1700
5         6              2200
6         7              1700
7         8              2700
8         9              1000
9        10               500
10       11              3400
11       12               700
12       13              3200
13       14               500
14       15              2700
15       16              1700
16       17               700
17       18              1000
18       19              1900
19       20              3400

In [ ]:
# Revenue per cohort
query = """
WITH cohort AS (
    SELECT
        user_id,
        strftime('%Y-%m', MIN(session_date)) AS cohort_month
    FROM sessions
    GROUP BY user_id
)
SELECT
    c.cohort_month,
    SUM(s.fee) AS total_revenue
FROM sessions s
JOIN cohort c ON s.user_id = c.user_id
GROUP BY c.cohort_month
ORDER BY c.cohort_month;

"""

pd.read_sql(query, conne)

  cohort_month  total_revenue
0      2025-01          97300
1      2025-02         126000
2      2025-03         117100
3      2025-04         143400
4      2025-05         153600
5      2025-06         135700
6      2025-07          30400

In [ ]:
# Revenue per therapist
query = """
SELECT
    therapist_id,
    SUM(fee) AS total_revenue
FROM sessions
GROUP BY therapist_id
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conne)

    therapist_id  total_revenue
0             37          24300
1              8          22300
2             35          22200
3             12          22200
4             34          20900
5              9          20800
6              6          20800
7              4          20000
8             25          19700
9             22          19400
10             3          18900
11            45          18800
12            17          18700
13            13          18700
14            28          18200
15            44          18100
16            14          17900
17            49          17800
18            36          17700
19            41          17200
20            24          17200
21            42          16700
22            21          16700
23            10          16500
24            26          16400
25            20          16400
26            40          15800
27            43          15500
28            39          15500
29            33          15400
30            16          15200
31            47          15100
32            23          15000
33             1          15000
34            19          14900
35            30          14800
36            31          13700
37            29          13600
38            18          13600
39            32          13400
40            15          13400
41             7          13100
42             2          13000
43            38          12900
44             5          11800
45            46          11100
46            27          10500
47            11           8900
48            48           7800

In [ ]:

# If a therapist completed more than 10 sessions in a month we are providing 20% of the total revenue as the bonus calculate monthly bonus for them.

query = """
SELECT
    therapist_id,
    strftime('%Y-%m', session_date) AS month,
    COUNT(*) AS total_sessions,
    SUM(fee) AS total_revenue,

    CASE
        WHEN COUNT(*) > 10
        THEN SUM(fee) * 0.2
        ELSE 0
    END AS bonus

FROM sessions
GROUP BY therapist_id, month
order by total_sessions desc;
"""

result = pd.read_sql_query(query, conne)
result

     therapist_id    month  total_sessions  total_revenue  bonus
0              22  2025-03               9           6200      0
1              47  2025-05               9           6300      0
2               4  2025-06               8           5800      0
3               9  2025-03               8           6200      0
4              17  2025-03               8           4700      0
..            ...      ...             ...            ...    ...
322            46  2025-01               1            500      0
323            47  2025-03               1            500      0
324            47  2025-07               1            500      0
325            48  2025-01               1            700      0
326            48  2025-05               1            500      0

[327 rows x 5 columns]

In [ ]:
# Identify at which session most users drop off and provide % distribution
query = """
SELECT
    session_number,
    COUNT(DISTINCT user_id) AS users
FROM sessions
GROUP BY session_number
ORDER BY session_number;
"""

df_sessions = pd.read_sql_query(query, conne)


df_sessions['drop_off_users'] = df_sessions['users'].shift(1) - df_sessions['users']


df_sessions['drop_off_%'] = (
    df_sessions['drop_off_users'] / df_sessions['users'].shift(1) * 100
).round(2)

df_sessions

   session_number  users  drop_off_users  drop_off_%
0               1    500             NaN         NaN
1               2    281           219.0       43.80
2               3    169           112.0       39.86
3               4     97            72.0       42.60
4               5     48            49.0       50.52

**all python question**

In [ ]:
df = sessions.merge(users, on='user_id', how='left')
df = df.merge(feedback, on='session_id', how='left')

df.head(10)

,session_id,user_id,session_date,session_number,therapist_id,fee,valid_sequence,signup_date,source,rating,review_text
0,1,1,2025-04-27,1,46,1000,1.0,2025-04-13,Google,3.0,Sample review text
1,2,2,2025-07-04,1,35,700,1.0,2025-06-29,Instagram,5.0,Sample review text
2,3,3,2025-04-15,1,26,500,1.0,2025-04-03,Google,5.0,Sample review text
3,4,4,2025-01-19,1,41,1000,1.0,2025-01-15,Instagram,2.0,Sample review text
4,5,4,2025-01-28,2,45,700,1.0,2025-01-15,Instagram,NaN,NaN
5,6,4,2025-02-10,3,36,500,1.0,2025-01-15,Instagram,5.0,Sample review text
6,7,5,2025-04-28,1,37,700,1.0,2025-04-17,Organic,NaN,NaN
7,8,5,2025-05-09,2,49,1000,1.0,2025-04-17,Organic,2.0,Sample review text
8,9,6,2025-03-19,1,49,700,1.0,2025-03-13,Instagram,1.0,Sample review text
9,10,6,2025-03-28,2,32,1000,1.0,2025-03-13,Instagram,2.0,Sample review text

In [ ]:
# Handle missing values
df.isnull().sum()

session_id                  0
user_id                     0
session_date                0
session_number              0
therapist_id                0
fee                         0
valid_sequence              0
rating                      0
review_text                 0
retained                    0
user_lifetime_sessions      0
avg_rating                  0
days_between_sessions     455
sequence_check              0
dtype: int64

In [ ]:
df.head(11)

,session_id,user_id,session_date,session_number,therapist_id,fee,valid_sequence,rating,review_text,retained,user_lifetime_sessions,avg_rating,days_between_sessions,sequence_check
0,1,1,2025-04-27,1,46,1000,10.0,3,Sample review text,0,1,3.000000,NaN,1.0
1,2,2,2025-07-04,1,35,700,10.0,5,Sample review text,0,1,5.000000,NaN,1.0
2,3,3,2025-04-15,1,26,500,10.0,5,Sample review text,0,1,5.000000,NaN,1.0
3,4,4,2025-01-19,1,41,1000,10.0,2,Sample review text,0,2,3.500000,NaN,1.0
4,6,4,2025-02-10,3,36,500,1.0,5,Sample review text,1,2,3.500000,22.0,2.0
5,8,5,2025-05-09,2,49,1000,1.0,2,Sample review text,1,1,2.000000,NaN,1.0
6,9,6,2025-03-19,1,49,700,10.0,1,Sample review text,0,3,1.333333,NaN,1.0
7,10,6,2025-03-28,2,32,1000,1.0,2,Sample review text,1,3,1.333333,9.0,1.0
8,11,6,2025-04-04,3,13,500,1.0,1,Sample review text,1,3,1.333333,7.0,1.0
9,12,7,2025-01-26,1,30,500,10.0,4,Sample review text,0,3,2.666667,NaN,1.0
10,13,7,2025-01-29,2,20,500,1.0,3,Sample review text,1,3,2.666667,3.0,1.0

In [ ]:
# Filling rating data with taking average
df['rating'] = df['rating'].fillna(df['rating'].mean())
df.head(11)

,session_id,user_id,session_date,session_number,therapist_id,fee,valid_sequence,signup_date,source,rating,review_text,days_between_sessions
0,1,1,2025-04-27,1,46,1000,1.0,2025-04-13,Google,3.000000,Sample review text,0.0
1,2,2,2025-07-04,1,35,700,1.0,2025-06-29,Instagram,5.000000,Sample review text,0.0
2,3,3,2025-04-15,1,26,500,1.0,2025-04-03,Google,5.000000,Sample review text,0.0
3,4,4,2025-01-19,1,41,1000,1.0,2025-01-15,Instagram,2.000000,Sample review text,0.0
4,5,4,2025-01-28,2,45,700,1.0,2025-01-15,Instagram,3.040089,NaN,9.0
5,6,4,2025-02-10,3,36,500,1.0,2025-01-15,Instagram,5.000000,Sample review text,13.0
6,7,5,2025-04-28,1,37,700,1.0,2025-04-17,Organic,3.040089,NaN,0.0
7,8,5,2025-05-09,2,49,1000,1.0,2025-04-17,Organic,2.000000,Sample review text,11.0
8,9,6,2025-03-19,1,49,700,1.0,2025-03-13,Instagram,1.000000,Sample review text,0.0
9,10,6,2025-03-28,2,32,1000,1.0,2025-03-13,Instagram,2.000000,Sample review text,9.0
10,11,6,2025-04-04,3,13,500,1.0,2025-03-13,Instagram,1.000000,Sample review text,7.0

In [ ]:
df = df.sort_values(['user_id', 'session_date'])
df['days_between_sessions'] = df.groupby('user_id')['session_date'].diff().dt.days
df['days_between_sessions'] = df['days_between_sessions'].fillna(0)
df.head(11)

,session_id,user_id,session_date,session_number,therapist_id,fee,valid_sequence,signup_date,source,rating,review_text,days_between_sessions
0,1,1,2025-04-27,1,46,1000,1.0,2025-04-13,Google,3.000000,Sample review text,0.0
1,2,2,2025-07-04,1,35,700,1.0,2025-06-29,Instagram,5.000000,Sample review text,0.0
2,3,3,2025-04-15,1,26,500,1.0,2025-04-03,Google,5.000000,Sample review text,0.0
3,4,4,2025-01-19,1,41,1000,1.0,2025-01-15,Instagram,2.000000,Sample review text,0.0
4,5,4,2025-01-28,2,45,700,1.0,2025-01-15,Instagram,3.040089,No Review,9.0
5,6,4,2025-02-10,3,36,500,1.0,2025-01-15,Instagram,5.000000,Sample review text,13.0
6,7,5,2025-04-28,1,37,700,1.0,2025-04-17,Organic,3.040089,No Review,0.0
7,8,5,2025-05-09,2,49,1000,1.0,2025-04-17,Organic,2.000000,Sample review text,11.0
8,9,6,2025-03-19,1,49,700,1.0,2025-03-13,Instagram,1.000000,Sample review text,0.0
9,10,6,2025-03-28,2,32,1000,1.0,2025-03-13,Instagram,2.000000,Sample review text,9.0
10,11,6,2025-04-04,3,13,500,1.0,2025-03-13,Instagram,1.000000,Sample review text,7.0

In [ ]:
df['review_text'] = df['review_text'].fillna('No Review')
df.head(21)

,session_id,user_id,session_date,session_number,therapist_id,fee,valid_sequence,signup_date,source,rating,review_text,days_between_sessions
0,1,1,2025-04-27,1,46,1000,1.0,2025-04-13,Google,3.000000,Sample review text,0.0
1,2,2,2025-07-04,1,35,700,1.0,2025-06-29,Instagram,5.000000,Sample review text,0.0
2,3,3,2025-04-15,1,26,500,1.0,2025-04-03,Google,5.000000,Sample review text,0.0
3,4,4,2025-01-19,1,41,1000,1.0,2025-01-15,Instagram,2.000000,Sample review text,0.0
4,5,4,2025-01-28,2,45,700,1.0,2025-01-15,Instagram,3.040089,No Review,9.0
5,6,4,2025-02-10,3,36,500,1.0,2025-01-15,Instagram,5.000000,Sample review text,13.0
6,7,5,2025-04-28,1,37,700,1.0,2025-04-17,Organic,3.040089,No Review,0.0
7,8,5,2025-05-09,2,49,1000,1.0,2025-04-17,Organic,2.000000,Sample review text,11.0
8,9,6,2025-03-19,1,49,700,1.0,2025-03-13,Instagram,1.000000,Sample review text,0.0
9,10,6,2025-03-28,2,32,1000,1.0,2025-03-13,Instagram,2.000000,Sample review text,9.0
10,11,6,2025-04-04,3,13,500,1.0,2025-03-13,Instagram,1.000000,Sample review text,7.0
11,12,7,2025-01-26,1,30,500,1.0,2025-01-21,Organic,4.000000,Sample review text,0.0
12,13,7,2025-01-29,2,20,500,1.0,2025-01-21,Organic,3.000000,Sample review text,3.0
13,14,7,2025-02-09,3,13,700,1.0,2025-01-21,Organic,1.000000,Sample review text,11.0
14,15,8,2025-04-16,1,41,500,1.0,2025-04-13,Organic,2.000000,Sample review text,0.0
15,16,8,2025-04-21,2,7,500,1.0,2025-04-13,Organic,2.000000,Sample review text,5.0
16,17,8,2025-05-05,3,31,700,1.0,2025-04-13,Organic,2.000000,Sample review text,14.0
17,18,8,2025-05-11,4,47,1000,1.0,2025-04-13,Organic,3.000000,Sample review text,6.0
18,19,9,2025-05-09,1,12,1000,1.0,2025-05-02,Instagram,4.000000,Sample review text,0.0
19,20,10,2025-03-29,1,36,500,1.0,2025-03-16,Google,4.000000,Sample review text,0.0
20,21,11,2025-04-09,1,45,1000,1.0,2025-03-29,Organic,4.000000,Sample review text,0.0

In [ ]:
# above all  handled missing values
df.isnull().sum()

session_id               0
user_id                  0
session_date             0
session_number           0
therapist_id             0
fee                      0
valid_sequence           0
signup_date              0
source                   0
rating                   0
review_text              0
days_between_sessions    0
dtype: int64

In [ ]:
#Remove duplicates if present
df.duplicated().sum()

# no duplicates present

np.int64(0)

In [ ]:
# Validate session_number sequence
sessions = sessions.sort_values(['user_id','session_number'])

sessions['valid_sequence'] = sessions.groupby('user_id')['session_number'].diff().fillna(1)

invalid = sessions[sessions['valid_sequence'] != 1]
sessions.head(20)

,session_id,user_id,session_date,session_number,therapist_id,fee,valid_sequence
0,1,1,2025-04-27,1,46,1000,1.0
1,2,2,2025-07-04,1,35,700,1.0
2,3,3,2025-04-15,1,26,500,1.0
3,4,4,2025-01-19,1,41,1000,1.0
4,5,4,2025-01-28,2,45,700,1.0
5,6,4,2025-02-10,3,36,500,1.0
6,7,5,2025-04-28,1,37,700,1.0
7,8,5,2025-05-09,2,49,1000,1.0
8,9,6,2025-03-19,1,49,700,1.0
9,10,6,2025-03-28,2,32,1000,1.0
10,11,6,2025-04-04,3,13,500,1.0
11,12,7,2025-01-26,1,30,500,1.0
12,13,7,2025-01-29,2,20,500,1.0
13,14,7,2025-02-09,3,13,700,1.0
14,15,8,2025-04-16,1,41,500,1.0
15,16,8,2025-04-21,2,7,500,1.0
16,17,8,2025-05-05,3,31,700,1.0
17,18,8,2025-05-11,4,47,1000,1.0
18,19,9,2025-05-09,1,12,1000,1.0
19,20,10,2025-03-29,1,36,500,1.0

In [ ]:
# Average rating per therapist
avg_rating_therapist = df.groupby('therapist_id')['rating'].mean()

avg_rating_therapist

therapist_id
1     3.269488
2     3.061182
3     3.006168
4     3.115733
5     2.942511
6     3.045737
7     2.962262
8     3.138679
9     2.865215
10    3.236384
11    3.008591
12    2.905345
13    2.695391
14    3.340015
15    2.953353
16    3.166335
17    3.041545
18    3.144766
19    3.577156
20    3.091685
21    2.796553
22    3.044629
23    3.003818
24    2.715015
25    2.886414
26    2.960012
27    3.788578
28    2.766414
29    3.589497
30    3.480008
31    3.004454
32    3.124722
33    3.101842
34    3.188155
35    2.867598
36    3.130803
37    3.073775
38    3.104009
39    2.810022
40    3.056013
41    2.633352
42    2.836545
43    3.099056
44    2.644811
45    2.965015
46    3.274684
47    3.049099
48    2.840015
49    3.176689
Name: rating, dtype: float64

In [ ]:
# Correlation between rating and retention
df = sessions.merge(feedback, on='session_id')

df['retained'] = df['session_number'] > 1

df[['rating','retained']].corr()

            rating  retained
rating    1.000000 -0.020582
retained -0.020582  1.000000

In [ ]:
# create user_lifetime_sessions

df['user_lifetime_sessions'] = df.groupby('user_id')['session_id'].transform('count')

In [ ]:
# create avg_rating

df['avg_rating'] = df.groupby('user_id')['rating'].transform('mean')

In [ ]:
# create days_between_sessions

df = df.sort_values(['user_id', 'session_date'])
df['session_date'] = pd.to_datetime(df['session_date'])
df['days_between_sessions'] = df.groupby('user_id')['session_date'].diff().dt.days

In [ ]:
df.head(21)

,session_id,user_id,session_date,session_number,therapist_id,fee,valid_sequence,rating,review_text,retained,user_lifetime_sessions
0,1,1,2025-04-27,1,46,1000,1.0,3,Sample review text,False,1
1,2,2,2025-07-04,1,35,700,1.0,5,Sample review text,False,1
2,3,3,2025-04-15,1,26,500,1.0,5,Sample review text,False,1
3,4,4,2025-01-19,1,41,1000,1.0,2,Sample review text,False,2
4,6,4,2025-02-10,3,36,500,1.0,5,Sample review text,True,2
5,8,5,2025-05-09,2,49,1000,1.0,2,Sample review text,True,1
6,9,6,2025-03-19,1,49,700,1.0,1,Sample review text,False,3
7,10,6,2025-03-28,2,32,1000,1.0,2,Sample review text,True,3
8,11,6,2025-04-04,3,13,500,1.0,1,Sample review text,True,3
9,12,7,2025-01-26,1,30,500,1.0,4,Sample review text,False,3
10,13,7,2025-01-29,2,20,500,1.0,3,Sample review text,True,3
11,14,7,2025-02-09,3,13,700,1.0,1,Sample review text,True,3
12,15,8,2025-04-16,1,41,500,1.0,2,Sample review text,False,4
13,16,8,2025-04-21,2,7,500,1.0,2,Sample review text,True,4
14,17,8,2025-05-05,3,31,700,1.0,2,Sample review text,True,4
15,18,8,2025-05-11,4,47,1000,1.0,3,Sample review text,True,4
16,19,9,2025-05-09,1,12,1000,1.0,4,Sample review text,False,1
17,20,10,2025-03-29,1,36,500,1.0,4,Sample review text,False,1
18,21,11,2025-04-09,1,45,1000,1.0,4,Sample review text,False,5
19,22,11,2025-04-16,2,39,700,1.0,2,Sample review text,True,5
20,23,11,2025-04-28,3,35,500,1.0,2,Sample review text,True,5

In [ ]:
df.describe()

,session_id,user_id,session_date,session_number,therapist_id,fee,valid_sequence,rating,user_lifetime_sessions,avg_rating,days_between_sessions
count,898.000000,898.000000,898,898.000000,898.000000,898.000000,898.0,898.000000,898.000000,898.000000,443.000000
mean,539.545657,249.665924,2025-04-18 07:57:51.714922240,2.028953,24.752784,735.189310,1.0,3.040089,2.670379,3.040089,9.361174
min,1.000000,1.000000,2025-01-08 00:00:00,1.000000,1.000000,500.000000,1.0,1.000000,1.000000,1.000000,3.000000
25%,266.250000,127.000000,2025-03-06 00:00:00,1.000000,13.000000,500.000000,1.0,2.000000,2.000000,2.333333,6.000000
50%,543.000000,256.500000,2025-04-20 12:00:00,2.000000,24.500000,700.000000,1.0,3.000000,3.000000,3.000000,9.000000
75%,807.750000,373.750000,2025-05-31 00:00:00,3.000000,37.000000,1000.000000,1.0,4.000000,4.000000,3.750000,12.000000
max,1095.000000,500.000000,2025-08-17 00:00:00,5.000000,49.000000,1000.000000,1.0,5.000000,5.000000,5.000000,38.000000
std,314.415943,144.113736,NaN,1.173494,13.963127,208.696164,0.0,1.412066,1.312164,1.034157,4.689985

In [ ]:
df.to_csv("final_data.csv", index=False)
df

,session_id,user_id,session_date,session_number,therapist_id,fee,valid_sequence,rating,review_text,retained,user_lifetime_sessions
0,1,1,2025-04-27,1,46,1000,1.0,3,Sample review text,False,1
1,2,2,2025-07-04,1,35,700,1.0,5,Sample review text,False,1
2,3,3,2025-04-15,1,26,500,1.0,5,Sample review text,False,1
3,4,4,2025-01-19,1,41,1000,1.0,2,Sample review text,False,2
4,6,4,2025-02-10,3,36,500,1.0,5,Sample review text,True,2
...,...,...,...,...,...,...,...,...,...,...,...
893,1091,496,2025-03-22,1,6,500,1.0,5,Sample review text,False,1
894,1092,497,2025-03-17,1,5,700,1.0,3,Sample review text,False,1
895,1093,498,2025-06-23,1,48,500,1.0,5,Sample review text,False,1
896,1094,499,2025-06-25,1,2,500,1.0,2,Sample review text,False,1
897,1095,500,2025-03-24,1,13,500,1.0,4,Sample review text,False,1

Looker Studio Dashboard.

https://lookerstudio.google.com/reporting/7436b277-1cb8-461e-b580-57575042e82f

1. Why are users dropping off?
Most users drop after the first session, which shows the initial experience is not strong enough.
It could be due to poor onboarding, mismatch with therapist, or unclear expectations.
Users are not getting enough value early, so they don't continue. Or  may be first is free or dicounted thats why they taken and later not continue it would be possible.

2. Which acquisition source performs best?
Based on user activity and engagement patterns, sources like Google and Instagram seem to bring more active users.
These users are more likely to continue sessions compared to others.
So, these channels appear to perform better in terms of retention.

3. How can we improve retention?
Improving the first session experience is the most important step.
Better therapist matching and follow-up engagement can help users stay longer.
Also, improving session quality can increase ratings, which directly improves retention.

4. What metric would you track daily ?
I would track retention at Session 2 on a daily basis.
It shows whether users are continuing after their first experience.
This helps quickly identify if there is a drop in early engagement.